# Generated by Django 5.2.8 on 2025-11-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TareaRegistrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateField(help_text='Fecha en que se realizó la tarea')),
                ('co2_evitado', models.DecimalField(decimal_places=2, help_text='Kg de CO₂ evitado en esta acción específica', max_digits=6)),
                ('puntos_ganados', models.IntegerField(help_text='Puntos ganados por esta acción')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre la tarea realizada')),
                ('foto', models.ImageField(blank=True, help_text='Foto opcional de la tarea realizada', null=True, upload_to='tareas/')),
                ('validada', models.BooleanField(default=True, help_text='Indica si la tarea ha sido validada')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró la tarea')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarea Registrada',
                'verbose_name_plural': 'Tareas Registradas',
                'ordering': ['-fecha_realizacion', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='TipoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la tarea ecológica', max_length=100)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la tarea')),
                ('categoria', models.CharField(choices=[('reciclaje', 'Reciclaje'), ('transporte', 'Transporte Sustentable'), ('energia', 'Ahorro de Energía'), ('agua', 'Ahorro de Agua'), ('alimentacion', 'Alimentación Sustentable'), ('otro', 'Otro')], default='otro', help_text='Categoría a la que pertenece la tarea', max_length=20)),
                ('co2_evitado_por_accion', models.DecimalField(decimal_places=2, default=0.0, help_text='Kg de CO₂ evitado por realizar esta acción (valor base)', max_digits=6)),
                ('puntos_otorgados', models.IntegerField(default=10, help_text='Puntos que se otorgan al completar esta tarea')),
                ('icono', models.CharField(blank=True, help_text='Nombre del icono para mostrar en la interfaz', max_length=50)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la tarea está disponible para los usuarios')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Tarea',
                'verbose_name_plural': 'Tipos de Tareas',
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
