# Generated by Django 5.2.8 on 2025-11-23 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tareas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarearegistrada',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que realizó la tarea', on_delete=django.db.models.deletion.CASCADE, related_name='tareas_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarearegistrada',
            name='tipo_tarea',
            field=models.ForeignKey(help_text='Tipo de tarea realizada', on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='tareas.tipotarea'),
        ),
    ]
