# Generated by Django 5.2.8 on 2025-11-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del grupo', max_length=100, unique=True)),
                ('descripcion', models.TextField(help_text='Descripción del grupo y sus objetivos')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='grupos/')),
                ('publico', models.BooleanField(default=True, help_text='Si es público, cualquiera puede unirse')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del logro/insignia', max_length=100)),
                ('descripcion', models.TextField(help_text='Descripción de cómo obtener este logro')),
                ('tipo', models.CharField(choices=[('bronce', 'Bronce'), ('plata', 'Plata'), ('oro', 'Oro'), ('platino', 'Platino')], default='bronce', help_text='Tipo/nivel del logro', max_length=20)),
                ('icono', models.ImageField(blank=True, help_text='Imagen del logro/insignia', null=True, upload_to='logros/')),
                ('puntos_requeridos', models.IntegerField(default=0, help_text='Puntos totales necesarios para obtener este logro')),
                ('tareas_requeridas', models.IntegerField(default=0, help_text='Cantidad de tareas completadas necesarias')),
                ('co2_requerido', models.DecimalField(decimal_places=2, default=0.0, help_text='Kg de CO₂ evitado necesarios', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'ordering': ['tipo', '-puntos_requeridos'],
            },
        ),
        migrations.CreateModel(
            name='LogroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtencion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se obtuvo el logro')),
            ],
            options={
                'verbose_name': 'Logro de Usuario',
                'verbose_name_plural': 'Logros de Usuarios',
                'ordering': ['-fecha_obtencion'],
            },
        ),
        migrations.CreateModel(
            name='MiembroGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('es_admin', models.BooleanField(default=False, help_text='Indica si el miembro es administrador del grupo')),
            ],
            options={
                'verbose_name': 'Miembro de Grupo',
                'verbose_name_plural': 'Miembros de Grupos',
                'ordering': ['-fecha_union'],
            },
        ),
    ]
