# Generated by Django 5.2.8 on 2025-11-23 21:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('admin', 'Administrador')], default='usuario', help_text='Rol del usuario en el sistema', max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento del usuario', null=True)),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono del usuario', max_length=15)),
                ('avatar', models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='avatars/')),
                ('puntos_totales', models.IntegerField(default=0, help_text='Puntos acumulados por el usuario')),
                ('nivel', models.IntegerField(default=1, help_text='Nivel actual del usuario (calculado según puntos)')),
                ('co2_total_evitado', models.DecimalField(decimal_places=2, default=0.0, help_text='Total de kg de CO₂ evitados por el usuario', max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del usuario')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actualización del perfil')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el usuario está activo en el sistema')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-fecha_creacion'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
